import { buildCompileBlock, buildGraphWiring } from "./graph-wiring";
import { lines, pythonId } from "./emit";
import { buildAllNodeFunctions } from "./node-functions";
import { buildMermaidComment } from "./mermaid";
import { buildWorkflowSummary } from "./summary";
import {
  hasBlockingErrors,
  validateWorkflow,
} from "../workflow/validation";
import type { WorkflowGraph } from "../workflow/types";

export type CodegenResult =
  | { ok: true; code: string }
  | { ok: false; issues: string[] };

export function generatePython(graph: WorkflowGraph): CodegenResult {
  const validation = validateWorkflow(graph);
  if (hasBlockingErrors(validation)) {
    return {
      ok: false,
      issues: validation
        .filter((v) => v.severity === "error")
        .map((v) => v.message),
    };
  }

  if (graph.nodes.length === 0) {
    return { ok: false, issues: ["Add at least one node."] };
  }

  const idToPy = new Map<string, string>();
  graph.nodes.forEach((node, index) => {
    idToPy.set(node.id, pythonId(node.id, index));
  });

  const humanNodes = graph.nodes
    .filter((n) => n.type === "human")
    .map((n) => idToPy.get(n.id)!);

  const code = lines(
    '"""',
    "Generated by Agent Blueprint — LangGraph workflow.",
    "pip install langgraph langchain-openai langchain-core",
    "",
    buildWorkflowSummary(graph),
    '"""',
    "",
    "from typing import TypedDict",
    "",
    "from langchain_core.messages import HumanMessage, SystemMessage",
    "from langchain_openai import ChatOpenAI",
    "from langgraph.checkpoint.memory import MemorySaver",
    "from langgraph.graph import END, START, StateGraph",
    "",
    "",
    "class AgentState(TypedDict, total=False):",
    '    input: str',
    '    messages: list',
    '    tool_result: dict',
    '    done: bool',
    '    approved: bool',
    '    awaiting_human: bool',
    "",
    "",
    "def run_tool(name: str, state: AgentState) -> dict:",
    '    """Connect LangChain tools here."""',
    '    return {"tool": name, "status": "ok"}',
    "",
    "",
    buildAllNodeFunctions(graph.nodes, idToPy),
    "",
    "",
    "def build_graph():",
    indentBlock(buildGraphWiring(graph, idToPy)),
    indentBlock(buildCompileBlock(humanNodes)),
    "",
    "",
    'if __name__ == "__main__":',
    "    app = build_graph()",
    '    print(app.invoke({"input": "Hello from Agent Blueprint"}))',
    "",
    buildMermaidComment(graph),
  );

  return { ok: true, code };
}

function indentBlock(block: string): string {
  return block
    .split("\n")
    .map((line) => (line.length ? `    ${line}` : line))
    .join("\n");
}
